// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghhvsjrusobrsckhjtjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoaHZzanJ1c29icnNja2hqdGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODg0OTgsImV4cCI6MjA3NDU2NDQ5OH0.0V7MA-bPYOtIPef5ttQTXNFTI2PFVqWqY57-GP_sMdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});