// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihoqnrdtbcajffvbgsui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlob3FucmR0YmNhamZmdmJnc3VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MzM0ODQsImV4cCI6MjA3NjEwOTQ4NH0.MLBvzpMQomGqOxd5n1W_Ar3sYaXe7Mpoj0tea0-E17M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});